"""...

Revision ID: 25c363a279d2
Revises: 1ea9390f1a88
Create Date: 2025-04-21 21:48:14.623023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c363a279d2'
down_revision: Union[str, None] = '1ea9390f1a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'books', ['title'])
    op.drop_column('books', 'Title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('Title', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'title')
    # ### end Alembic commands ###
