name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      TOKEN_TIME: ${{ secrets.TOKEN_TIME }}

    steps:
      - name: Copy files from the repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev

      - name: Install Poetry
        run: pipx install poetry

      - name: Clear Poetry Cache
        run: poetry cache clear --all pypi

      - name: Install gssapi with Poetry
        run: poetry add gssapi@1.9.0

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run task test